print("Какой первый этап?")
a1 = input()
print("Какой второй этап?")
a2 = input()
print("Какой третий этап?")
a3 = input()
print("Четвертый?")
a4 = input()
print("Пятый?")
a5 = input()
print("Шестой")
a6 = input()
print("Седьмой?")
a7 = input()
print("Восьмой?")
a8 = input()
print("Девятый?")
a9 = input()
print("ДЕСЯТЫЙ?")
a10 = input()
print("ОДИННАДЦАТЫЙ!")
a11 = input()
print(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, sep='=>')
